export const BADGE_DEFINITIONS = [
  {
    id: 'first_dram',
    name: 'First Dram',
    description: 'Log your very first whisky check-in',
    icon: '🥃',
    criteria_type: 'checkin_count',
    criteria_value: 1,
  },
  {
    id: 'ten_drams',
    name: 'Ten Drams',
    description: 'Log 10 whisky check-ins',
    icon: '🔟',
    criteria_type: 'checkin_count',
    criteria_value: 10,
  },
  {
    id: 'fifty_drams',
    name: 'Fifty Drams',
    description: 'Log 50 whisky check-ins',
    icon: '🏅',
    criteria_type: 'checkin_count',
    criteria_value: 50,
  },
  {
    id: 'peat_head',
    name: 'Peat Head',
    description: 'Try 5 whiskies from the Islay region',
    icon: '💨',
    criteria_type: 'region_count',
    criteria_value: 5,
  },
  {
    id: 'bourbon_trail',
    name: 'Bourbon Trail',
    description: 'Try 5 different Bourbons',
    icon: '🌽',
    criteria_type: 'bourbon_count',
    criteria_value: 5,
  },
  {
    id: 'globe_trotter',
    name: 'Globe Trotter',
    description: 'Try whiskies from 5 different countries',
    icon: '🌍',
    criteria_type: 'country_count',
    criteria_value: 5,
  },
  {
    id: 'explorer',
    name: 'Explorer',
    description: 'Try whiskies from 3 different regions',
    icon: '🧭',
    criteria_type: 'region_variety',
    criteria_value: 3,
  },
  {
    id: 'first_drop',
    name: 'First Drop',
    description: 'Get your first whisky submission approved',
    icon: '💧',
    criteria_type: 'submitted_count',
    criteria_value: 1,
  },
  {
    id: 'nosing_around',
    name: 'Nosing Around',
    description: 'Get 5 whisky submissions approved',
    icon: '👃',
    criteria_type: 'submitted_count',
    criteria_value: 5,
  },
  {
    id: 'whisky_scout',
    name: 'Whisky Scout',
    description: 'Get 10 whisky submissions approved',
    icon: '🔍',
    criteria_type: 'submitted_count',
    criteria_value: 10,
  },
  {
    id: 'curator',
    name: 'Curator',
    description: 'Get 25 whisky submissions approved',
    icon: '📚',
    criteria_type: 'submitted_count',
    criteria_value: 25,
  },
  {
    id: 'cellar_master',
    name: 'Cellar Master',
    description: 'Get 50 whisky submissions approved',
    icon: '🗝️',
    criteria_type: 'submitted_count',
    criteria_value: 50,
  },
  {
    id: 'distillers_choice',
    name: "Distiller's Choice",
    description: 'Get 100 whisky submissions approved',
    icon: '🏆',
    criteria_type: 'submitted_count',
    criteria_value: 100,
  },
  // Logging milestones
  {
    id: 'century_dram',
    name: 'Century Dram',
    description: 'Log 100 check-ins',
    icon: '🎯',
    criteria_type: 'checkin_count',
    criteria_value: 100,
  },
  {
    id: 'quarter_master',
    name: 'Quarter Master',
    description: 'Log 250 check-ins',
    icon: '🏅',
    criteria_type: 'checkin_count',
    criteria_value: 250,
  },
  {
    id: 'five_hundred_club',
    name: '500 Club',
    description: 'Log 500 check-ins',
    icon: '🔥',
    criteria_type: 'checkin_count',
    criteria_value: 500,
  },
  // Style explorer
  {
    id: 'rye_not',
    name: 'Rye Not?',
    description: 'Try 10 rye whiskies',
    icon: '🌾',
    criteria_type: 'rye_count',
    criteria_value: 10,
  },
  {
    id: 'rising_sun',
    name: 'Rising Sun',
    description: 'Try 5 Japanese whiskies',
    icon: '🌸',
    criteria_type: 'japanese_count',
    criteria_value: 5,
  },
  {
    id: 'emerald_isle',
    name: 'Emerald Isle',
    description: 'Try 5 Irish whiskies',
    icon: '☘️',
    criteria_type: 'irish_count',
    criteria_value: 5,
  },
  {
    id: 'speyside_scholar',
    name: 'Speyside Scholar',
    description: 'Try 5 Speyside whiskies',
    icon: '🎓',
    criteria_type: 'speyside_count',
    criteria_value: 5,
  },
  {
    id: 'highland_hero',
    name: 'Highland Hero',
    description: 'Try 5 Highland whiskies',
    icon: '🏔️',
    criteria_type: 'highlands_count',
    criteria_value: 5,
  },
  {
    id: 'malt_devotee',
    name: 'Malt Devotee',
    description: 'Try 20 single malts',
    icon: '🥃',
    criteria_type: 'single_malt_count',
    criteria_value: 20,
  },
  {
    id: 'bourbon_connoisseur',
    name: 'Bourbon Connoisseur',
    description: 'Try 25 different bourbons',
    icon: '🌽',
    criteria_type: 'bourbon_count',
    criteria_value: 25,
  },
  // Connoisseur
  {
    id: 'old_faithful',
    name: 'Old Faithful',
    description: 'Try a whisky aged 18+ years',
    icon: '⏳',
    criteria_type: 'age_18_plus',
    criteria_value: 1,
  },
  {
    id: 'ancient_one',
    name: 'Ancient One',
    description: 'Try a whisky aged 25+ years',
    icon: '🏛️',
    criteria_type: 'age_25_plus',
    criteria_value: 1,
  },
  {
    id: 'cask_strength',
    name: 'Cask Strength',
    description: 'Try a whisky over 55% ABV',
    icon: '💪',
    criteria_type: 'high_abv',
    criteria_value: 1,
  },
  {
    id: 'world_tour',
    name: 'World Tour',
    description: 'Try whiskies from all 8 countries',
    icon: '🌐',
    criteria_type: 'country_count',
    criteria_value: 8,
  },
  // Social & quality
  {
    id: 'five_star_general',
    name: 'Five Star General',
    description: 'Give out 10 five-star ratings',
    icon: '⭐',
    criteria_type: 'five_star_count',
    criteria_value: 10,
  },
  {
    id: 'critic',
    name: 'Critic',
    description: 'Write tasting notes on 20 check-ins',
    icon: '📝',
    criteria_type: 'noted_checkin_count',
    criteria_value: 20,
  },
  {
    id: 'social_dram',
    name: 'Social Dram',
    description: 'Follow 10 other users',
    icon: '👥',
    criteria_type: 'following_count',
    criteria_value: 10,
  },
  {
    id: 'crowd_favorite',
    name: 'Crowd Favorite',
    description: 'Receive 25 likes on your check-ins',
    icon: '❤️',
    criteria_type: 'likes_received',
    criteria_value: 25,
  },
  // Collection
  {
    id: 'collector',
    name: 'Collector',
    description: 'Add 20 whiskies to your collection',
    icon: '📦',
    criteria_type: 'collection_count',
    criteria_value: 20,
  },
  {
    id: 'wish_lister',
    name: 'Wish Lister',
    description: 'Add 10 whiskies to your want list',
    icon: '🌠',
    criteria_type: 'want_count',
    criteria_value: 10,
  },
  {
    id: 'flavor_chaser',
    name: 'Flavor Chaser',
    description: 'Try whiskies covering 10 different flavor tags',
    icon: '🌈',
    criteria_type: 'flavor_variety',
    criteria_value: 10,
  },
];

export const WHISKY_REGIONS = [
  'Islay', 'Speyside', 'Highlands', 'Lowlands', 'Campbeltown',
  'Islands', 'Kentucky', 'Tennessee', 'Ireland', 'Japan',
  'Canada', 'India', 'Taiwan', 'Other',
];

export const WHISKY_COUNTRIES = [
  'Scotland', 'USA', 'Ireland', 'Japan', 'Canada',
  'India', 'Taiwan', 'Australia', 'Other',
];

import { WhiskyType } from '../types';

export const FLAVOR_TAGS = [
  // Smoke & Peat
  'Peaty', 'Smoky', 'Medicinal', 'Briny',
  // Sweet
  'Sweet', 'Vanilla', 'Caramel', 'Honey', 'Chocolate', 'Toffee',
  // Fruit
  'Fruity', 'Citrus', 'Apple / Pear', 'Stone Fruit', 'Dried Fruit', 'Tropical',
  // Spice
  'Spicy', 'Peppery', 'Cinnamon', 'Ginger',
  // Earthy / Woody
  'Woody / Oak', 'Nutty', 'Grainy', 'Herbal', 'Floral',
  // Rich
  'Sherry', 'Creamy', 'Buttery',
];

export const COUNTRY_TYPES: Record<string, WhiskyType[]> = {
  Scotland:  ['single_malt', 'blended'],
  USA:       ['bourbon', 'rye', 'other'],
  Ireland:   ['irish', 'blended', 'other'],
  Japan:     ['japanese', 'single_malt', 'blended', 'other'],
  Canada:    ['blended', 'rye', 'other'],
  India:     ['single_malt', 'blended', 'other'],
  Taiwan:    ['single_malt', 'other'],
  Australia: ['single_malt', 'blended', 'other'],
  Other:     ['single_malt', 'blended', 'bourbon', 'rye', 'irish', 'japanese', 'other'],
};

export const COUNTRY_REGIONS: Record<string, string[]> = {
  Scotland:  ['Speyside', 'Highlands', 'Islay', 'Lowlands', 'Campbeltown', 'Islands'],
  USA:       ['Kentucky', 'Tennessee', 'Other'],
  Ireland:   ['Other'],
  Japan:     ['Other'],
  Canada:    ['Other'],
  India:     ['Other'],
  Taiwan:    ['Other'],
  Australia: ['Other'],
  Other:     ['Other'],
};
